Repository tenstorrent/tt-xla, pull requests merged in 2025-07, with the labels that each got.

#760 Uplift third_party/tt-mlir to b440b006a763062301d97f532111b2a7a5bfe08c 2025-07-04
  third_party/CMakeLists.txt
Labels: uplift

#767 Uplift third_party/tt-mlir to 7e54f7fc197c05836602a929622de93df0e2f5a8 2025-07-06
  third_party/CMakeLists.txt
Labels: uplift

#769 Uplift third_party/tt-mlir to 107cac17757a708b85cbea8a064a4d45853064c5 2025-07-07
  third_party/CMakeLists.txt
Labels: uplift

#780 Uplift third_party/tt-mlir to 1c19d9cb0371b1ee04fa3ae8febc2532cf38b61d 2025-07-08
  third_party/CMakeLists.txt
Labels: uplift

#787 Uplift third_party/tt-mlir to a3520a573a462c7bd23b7e0f9d444782fa43186b 2025-07-09
  third_party/CMakeLists.txt
Labels: uplift

#799 Uplift third_party/tt-mlir to 42332a2b361f458595be7b91769a17b9a92b2fc7 2025-07-10
  third_party/CMakeLists.txt
Labels: uplift

#815 Update test durations based on latest nightly 2025-07-11
  .test_durations
Labels: tooling

#862 Uplift third_party/tt-mlir to 6266cbd70ea097cc56357b18babcdc648790f08a 2025-07-19
  third_party/CMakeLists.txt
Labels: uplift

#872 Uplift third_party/tt-mlir to 71d693a4074e06324d93e86957db0bf5fcdade47 2025-07-22
  third_party/CMakeLists.txt
Labels: uplift

#888 Uplift third_party/tt-mlir to bcc6c92b437f1ce7a31fdee5a760397ff4889ead 2025-07-23
  third_party/CMakeLists.txt
Labels: uplift

#779 Llama3.1 8 b paralel
  tests/jax/multi_chip/bounties/Llama_3.1-8B/.gitignore
  tests/jax/multi_chip/bounties/Llama_3.1-8B/README.md
  tests/jax/multi_chip/bounties/Llama_3.1-8B/check_outputs.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/__init__.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/config.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/convert_weights.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/generate_hf.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/generate_multi_chip.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/generate_single_chip.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/generation.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/llama/model.py
  tests/jax/multi_chip/bounties/Llama_3.1-8B/requirements.txt
Labels: bounty

#900 Uplift third_party/tt-mlir to fbeed2a9cb62dedd4902c950d3f13e4a88d22cba 2025-07-26
  third_party/CMakeLists.txt
Labels: uplift
